[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.deploy]
startCommand = "npm run start"

[environments.production.variables]
NODE_ENV = "production" 